### ISSUE TITLE
trigger some problems when running the training-estimating.py

### ISSUE THREAD

**Issue by BBge** [Lancern/asm2vec#1]
I try to run training-estimating.py as following
`python training-estimating.py`

But it triggers some problems:
\# of training functions: 3
\# of estimating functions: 3
Training complete.
Traceback (most recent call last):
  File "training-estimating.py", line 42, in <module>
    main()
  File "training-estimating.py", line 29, in main
    estimating_funcs_vec = list(map(lambda f: model.to_vec(f), estimating_funcs))
  File "training-estimating.py", line 29, in <lambda>
    estimating_funcs_vec = list(map(lambda f: model.to_vec(f), estimating_funcs))
  File "/home/bbge/Downloads/asm2vec-master/asm2vec/model.py", line 56, in to_vec
    vf = estimate_repo.funcs()[0]
IndexError: list index out of range

My python version is 3.7.3.

Could you figure out how to deal with it?
Thanks!

**Comment by BBge** [comment]
fixed it by activating a virtual env with python 3.7.4.
